### ISSUE TITLE
Collect remaining single-client 'sanity' tests

### ISSUE THREAD

**Issue by lsankar4033** [lsankar4033/stethoscope#22]
The currently planned single-client tests are:

| description   |                         status                        |
|----------|:-----------------------------------------------------:|
| responds to all req/resp methods  | done        |
| subscribed to the right gossipsub topics     | done |
| is running disc5 and is 'lookup-able' | in progress |
| re-gossips gossiped messages | TODO | 

This issue serves as a place to collect any remaining 'sanity' tests that we'd want when we put stethoscope in CI and share it with clients.

**Comment by djrtwo** [comment]
`Status` -- rumor dials peer
* success
    * 100% agree on all fields
    * rumor is behind on `finalized_epoch` but `finalized_root` is in same chain as peer
    * agree on `finalized_root`/`epoch`
        * peer ahead of rumor on `head_root`/`slot`
        * peer behind rumor on `head_root`/`slot`
* failure
    * with junk `fork_digest`
    * with junk `finalized_root` at `finalized_epoch` that peer should already know about

In the above, I'm assuming we can seed the client with state/messages to be able to tune the test. What is the extent of our capabilities here?

can we have peer dial rumor in such a test? doesn't seem immediately obvious how to generically do this across clients

**Comment by lsankar4033** [comment]
Documenting test groups here: https://hackmd.io/fBgz1UO7TsK_oAABtLNnlQ?view
